//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: CardSched.java
//

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com\born2go\lazzybee\algorithms\CardSched.h"
#include "java/lang/Math.h"

#define BONUS_EASY 1.4
#define MIN_FACTOR 1300

@interface ComBorn2goLazzybeeAlgorithmsCardSched ()

- (jint)_constrainedIvlWithInt:(jint)ivl
                    withDouble:(jdouble)prev;

@end

static IOSIntArray *ComBorn2goLazzybeeAlgorithmsCardSched_FACTOR_ADDITION_VALUES_;
J2OBJC_STATIC_FIELD_GETTER(ComBorn2goLazzybeeAlgorithmsCardSched, FACTOR_ADDITION_VALUES_, IOSIntArray *)

J2OBJC_STATIC_FIELD_GETTER(ComBorn2goLazzybeeAlgorithmsCardSched, BONUS_EASY, jdouble)

J2OBJC_STATIC_FIELD_GETTER(ComBorn2goLazzybeeAlgorithmsCardSched, MIN_FACTOR, jint)

__attribute__((unused)) static jint ComBorn2goLazzybeeAlgorithmsCardSched__constrainedIvlWithInt_withDouble_(ComBorn2goLazzybeeAlgorithmsCardSched *self, jint ivl, jdouble prev);

@interface ComBorn2goLazzybeeAlgorithmsCardSched_Card : NSObject

@end

J2OBJC_INITIALIZED_DEFN(ComBorn2goLazzybeeAlgorithmsCardSched)

@implementation ComBorn2goLazzybeeAlgorithmsCardSched

- (instancetype)init {
  ComBorn2goLazzybeeAlgorithmsCardSched_init(self);
  return self;
}

- (IOSObjectArray *)nextIvlStrLstWithComBorn2goLazzybeeAlgorithmsCardSched_Card:(id<ComBorn2goLazzybeeAlgorithmsCardSched_Card>)card {
  IOSObjectArray *ret = [IOSObjectArray arrayWithLength:4 type:NSString_class_()];
  for (jint i = 0; i < 4; i++) {
    IOSObjectArray_Set(ret, i, [self _nextIvlStrWithComBorn2goLazzybeeAlgorithmsCardSched_Card:card withInt:i]);
  }
  return ret;
}

- (NSString *)_nextIvlStrWithComBorn2goLazzybeeAlgorithmsCardSched_Card:(id<ComBorn2goLazzybeeAlgorithmsCardSched_Card>)card
                                                                withInt:(jint)ease {
  NSString *str;
  jint ivl = [self nextIvlBySecondsWithComBorn2goLazzybeeAlgorithmsCardSched_Card:card withInt:ease];
  if (ivl < ComBorn2goLazzybeeAlgorithmsCardSched_SECONDS_PERDAY) str = @"< 10min";
  else {
    jint day = ivl / ComBorn2goLazzybeeAlgorithmsCardSched_SECONDS_PERDAY;
    if (day <= 30) str = JreStrcat("I$", JavaLangMath_roundWithFloat_(day), @" day");
    else {
      jdouble month = day / 30;
      str = JreStrcat("D$", month, @" month");
      if (month > 12) {
        jdouble year = day / 365;
        str = JreStrcat("D$", year, @" year");
      }
    }
  }
  return str;
}

- (jint)nextIvlBySecondsWithComBorn2goLazzybeeAlgorithmsCardSched_Card:(id<ComBorn2goLazzybeeAlgorithmsCardSched_Card>)card
                                                               withInt:(jint)ease {
  if (ease == ComBorn2goLazzybeeAlgorithmsCardSched_EASE_AGAIN) {
    return 600;
  }
  else {
    return [self _nextIntervalByDaysWithComBorn2goLazzybeeAlgorithmsCardSched_Card:card withInt:ease] * ComBorn2goLazzybeeAlgorithmsCardSched_SECONDS_PERDAY;
  }
}

- (jint)_nextIntervalByDaysWithComBorn2goLazzybeeAlgorithmsCardSched_Card:(id<ComBorn2goLazzybeeAlgorithmsCardSched_Card>)card
                                                                  withInt:(jint)ease {
  JreAssert((ease > ComBorn2goLazzybeeAlgorithmsCardSched_EASE_AGAIN && ease <= ComBorn2goLazzybeeAlgorithmsCardSched_EASE_EASY), @"com\\born2go\\lazzybee\\algorithms\\CardSched.java:83 condition failed: assert (ease > EASE_AGAIN && ease <= EASE_EASY);");
  jlong delay = [self _daysLateWithComBorn2goLazzybeeAlgorithmsCardSched_Card:card];
  jint interval = 0;
  jdouble fct = [((id<ComBorn2goLazzybeeAlgorithmsCardSched_Card>) nil_chk(card)) getFactor] / 1000.0;
  jint ivl_hard = ComBorn2goLazzybeeAlgorithmsCardSched__constrainedIvlWithInt_withDouble_(self, JreFpToInt((([card getLast_ivl] + delay / 4) * 1.2)), [card getLast_ivl]);
  jint ivl_good = ComBorn2goLazzybeeAlgorithmsCardSched__constrainedIvlWithInt_withDouble_(self, JreFpToInt((([card getLast_ivl] + delay / 2) * fct)), ivl_hard);
  jint ivl_easy = ComBorn2goLazzybeeAlgorithmsCardSched__constrainedIvlWithInt_withDouble_(self, JreFpToInt((([card getLast_ivl] + delay) * fct * BONUS_EASY)), ivl_good);
  if (ease == ComBorn2goLazzybeeAlgorithmsCardSched_EASE_HARD) {
    interval = ivl_hard;
  }
  else if (ease == ComBorn2goLazzybeeAlgorithmsCardSched_EASE_GOOD) {
    interval = ivl_good;
  }
  else if (ease == ComBorn2goLazzybeeAlgorithmsCardSched_EASE_EASY) {
    interval = ivl_easy;
  }
  return interval;
}

- (jlong)_daysLateWithComBorn2goLazzybeeAlgorithmsCardSched_Card:(id<ComBorn2goLazzybeeAlgorithmsCardSched_Card>)card {
  if ([((id<ComBorn2goLazzybeeAlgorithmsCardSched_Card>) nil_chk(card)) getQueue] != 2) return 0;
  jlong due = [card getDue];
  ;
  jlong now = 123456789;
  jlong diff_day = (now - due) / ComBorn2goLazzybeeAlgorithmsCardSched_SECONDS_PERDAY;
  return JavaLangMath_maxWithLong_withLong_(0, diff_day);
}

- (jint)_constrainedIvlWithInt:(jint)ivl
                    withDouble:(jdouble)prev {
  return ComBorn2goLazzybeeAlgorithmsCardSched__constrainedIvlWithInt_withDouble_(self, ivl, prev);
}

- (void)answerCardWithComBorn2goLazzybeeAlgorithmsCardSched_Card:(id<ComBorn2goLazzybeeAlgorithmsCardSched_Card>)card
                                                         withInt:(jint)ease {
  jint nextIvl = [self nextIvlBySecondsWithComBorn2goLazzybeeAlgorithmsCardSched_Card:card withInt:ease];
  [((id<ComBorn2goLazzybeeAlgorithmsCardSched_Card>) nil_chk(card)) increaseRevCount];
  jlong current = 987654321;
  if (nextIvl < ComBorn2goLazzybeeAlgorithmsCardSched_SECONDS_PERDAY) {
    [card setQueueWithInt:1];
    [card setLast_ivlWithInt:0];
  }
  else {
    [card setQueueWithInt:2];
    [card setDueWithLong:current + nextIvl];
    [card setLast_ivlWithInt:[self _nextIntervalByDaysWithComBorn2goLazzybeeAlgorithmsCardSched_Card:card withInt:ease]];
  }
  [card setFactorWithInt:JavaLangMath_maxWithInt_withInt_(MIN_FACTOR, [card getFactor] + IOSIntArray_Get(nil_chk(ComBorn2goLazzybeeAlgorithmsCardSched_FACTOR_ADDITION_VALUES_), ease))];
}

+ (void)initialize {
  if (self == [ComBorn2goLazzybeeAlgorithmsCardSched class]) {
    JreStrongAssignAndConsume(&ComBorn2goLazzybeeAlgorithmsCardSched_FACTOR_ADDITION_VALUES_, [IOSIntArray newArrayWithInts:(jint[]){ -300, -150, 0, 150 } count:4]);
    J2OBJC_SET_INITIALIZED(ComBorn2goLazzybeeAlgorithmsCardSched)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "CardSched", NULL, 0x1, NULL, NULL },
    { "nextIvlStrLstWithComBorn2goLazzybeeAlgorithmsCardSched_Card:", "nextIvlStrLst", "[Ljava.lang.String;", 0x1, NULL, NULL },
    { "_nextIvlStrWithComBorn2goLazzybeeAlgorithmsCardSched_Card:withInt:", "_nextIvlStr", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "nextIvlBySecondsWithComBorn2goLazzybeeAlgorithmsCardSched_Card:withInt:", "nextIvlBySeconds", "I", 0x1, NULL, NULL },
    { "_nextIntervalByDaysWithComBorn2goLazzybeeAlgorithmsCardSched_Card:withInt:", "_nextIntervalByDays", "I", 0x1, NULL, NULL },
    { "_daysLateWithComBorn2goLazzybeeAlgorithmsCardSched_Card:", "_daysLate", "J", 0x4, NULL, NULL },
    { "_constrainedIvlWithInt:withDouble:", "_constrainedIvl", "I", 0x2, NULL, NULL },
    { "answerCardWithComBorn2goLazzybeeAlgorithmsCardSched_Card:withInt:", "answerCard", "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "REVLOG_LRN", "REVLOG_LRN", 0x18, "I", NULL, NULL, .constantValue.asInt = ComBorn2goLazzybeeAlgorithmsCardSched_REVLOG_LRN },
    { "REVLOG_REV", "REVLOG_REV", 0x18, "I", NULL, NULL, .constantValue.asInt = ComBorn2goLazzybeeAlgorithmsCardSched_REVLOG_REV },
    { "REVLOG_RELRN", "REVLOG_RELRN", 0x18, "I", NULL, NULL, .constantValue.asInt = ComBorn2goLazzybeeAlgorithmsCardSched_REVLOG_RELRN },
    { "REVLOG_CRAM", "REVLOG_CRAM", 0x18, "I", NULL, NULL, .constantValue.asInt = ComBorn2goLazzybeeAlgorithmsCardSched_REVLOG_CRAM },
    { "EASE_AGAIN", "EASE_AGAIN", 0x19, "I", NULL, NULL, .constantValue.asInt = ComBorn2goLazzybeeAlgorithmsCardSched_EASE_AGAIN },
    { "EASE_HARD", "EASE_HARD", 0x19, "I", NULL, NULL, .constantValue.asInt = ComBorn2goLazzybeeAlgorithmsCardSched_EASE_HARD },
    { "EASE_GOOD", "EASE_GOOD", 0x19, "I", NULL, NULL, .constantValue.asInt = ComBorn2goLazzybeeAlgorithmsCardSched_EASE_GOOD },
    { "EASE_EASY", "EASE_EASY", 0x19, "I", NULL, NULL, .constantValue.asInt = ComBorn2goLazzybeeAlgorithmsCardSched_EASE_EASY },
    { "SECONDS_PERDAY", "SECONDS_PERDAY", 0x1c, "I", NULL, NULL, .constantValue.asInt = ComBorn2goLazzybeeAlgorithmsCardSched_SECONDS_PERDAY },
    { "FACTOR_ADDITION_VALUES_", NULL, 0x1a, "[I", &ComBorn2goLazzybeeAlgorithmsCardSched_FACTOR_ADDITION_VALUES_, NULL, .constantValue.asLong = 0 },
    { "BONUS_EASY", "BONUS_EASY", 0x1a, "D", NULL, NULL, .constantValue.asDouble = BONUS_EASY },
    { "MIN_FACTOR", "MIN_FACTOR", 0x1a, "I", NULL, NULL, .constantValue.asInt = MIN_FACTOR },
  };
  static const char *inner_classes[] = {"Lcom.born2go.lazzybee.algorithms.CardSched$Card;"};
  static const J2ObjcClassInfo _ComBorn2goLazzybeeAlgorithmsCardSched = { 2, "CardSched", "com.born2go.lazzybee.algorithms", NULL, 0x1, 8, methods, 12, fields, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_ComBorn2goLazzybeeAlgorithmsCardSched;
}

@end

void ComBorn2goLazzybeeAlgorithmsCardSched_init(ComBorn2goLazzybeeAlgorithmsCardSched *self) {
  NSObject_init(self);
}

ComBorn2goLazzybeeAlgorithmsCardSched *new_ComBorn2goLazzybeeAlgorithmsCardSched_init() {
  ComBorn2goLazzybeeAlgorithmsCardSched *self = [ComBorn2goLazzybeeAlgorithmsCardSched alloc];
  ComBorn2goLazzybeeAlgorithmsCardSched_init(self);
  return self;
}

jint ComBorn2goLazzybeeAlgorithmsCardSched__constrainedIvlWithInt_withDouble_(ComBorn2goLazzybeeAlgorithmsCardSched *self, jint ivl, jdouble prev) {
  return JreFpToInt(JavaLangMath_maxWithDouble_withDouble_(ivl, prev + 1));
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComBorn2goLazzybeeAlgorithmsCardSched)

@implementation ComBorn2goLazzybeeAlgorithmsCardSched_Card

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getId", NULL, "I", 0x401, NULL, NULL },
    { "setIdWithInt:", "setId", "V", 0x401, NULL, NULL },
    { "getQuestion", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "setQuestionWithNSString:", "setQuestion", "V", 0x401, NULL, NULL },
    { "getAnswers", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "setAnswersWithNSString:", "setAnswers", "V", 0x401, NULL, NULL },
    { "getCategories", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "setCategoriesWithNSString:", "setCategories", "V", 0x401, NULL, NULL },
    { "getSubcat", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "setSubcatWithNSString:", "setSubcat", "V", 0x401, NULL, NULL },
    { "getStatus", NULL, "I", 0x401, NULL, NULL },
    { "setStatusWithInt:", "setStatus", "V", 0x401, NULL, NULL },
    { "getgId", NULL, "I", 0x401, NULL, NULL },
    { "setgIdWithInt:", "setgId", "V", 0x401, NULL, NULL },
    { "getQueue", NULL, "I", 0x401, NULL, NULL },
    { "setQueueWithInt:", "setQueue", "V", 0x401, NULL, NULL },
    { "getDue", NULL, "J", 0x401, NULL, NULL },
    { "setDueWithLong:", "setDue", "V", 0x401, NULL, NULL },
    { "getPackage", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "setPackageWithNSString:", "setPackage", "V", 0x401, NULL, NULL },
    { "getLevel", NULL, "I", 0x401, NULL, NULL },
    { "setLevelWithInt:", "setLevel", "V", 0x401, NULL, NULL },
    { "getRev_count", NULL, "I", 0x401, NULL, NULL },
    { "setRev_countWithInt:", "setRev_count", "V", 0x401, NULL, NULL },
    { "getUser_note", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "setUser_noteWithNSString:", "setUser_note", "V", 0x401, NULL, NULL },
    { "getLast_ivl", NULL, "I", 0x401, NULL, NULL },
    { "setLast_ivlWithInt:", "setLast_ivl", "V", 0x401, NULL, NULL },
    { "increaseRevCount", NULL, "V", 0x401, NULL, NULL },
    { "getFactor", NULL, "I", 0x401, NULL, NULL },
    { "setFactorWithInt:", "setFactor", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComBorn2goLazzybeeAlgorithmsCardSched_Card = { 2, "Card", "com.born2go.lazzybee.algorithms", "CardSched", 0x608, 31, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComBorn2goLazzybeeAlgorithmsCardSched_Card;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComBorn2goLazzybeeAlgorithmsCardSched_Card)
