/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDataServiceApiVoca.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API
// Classes:
//   GTLDataServiceApiVoca (0 custom class methods, 9 custom properties)

#import "GTLDataServiceApiVoca.h"

// ----------------------------------------------------------------------------
//
//   GTLDataServiceApiVoca
//

@implementation GTLDataServiceApiVoca
@dynamic a, check, gid, lEn, lVn, level, note, packages, q;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"lEn" : @"l_en",
    @"lVn" : @"l_vn"
  };
  return map;
}

@end
