/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDataServiceApiConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API

#import "GTLDataServiceApiConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeDataServiceApiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
