/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDataServiceApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API

#import "GTLDataServiceApiConstants.h"

#import "GTLDataServiceApiVoca.h"
#import "GTLDataServiceApiVocaCollection.h"

#import "GTLQueryDataServiceApi.h"
#import "GTLServiceDataServiceApi.h"
