/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDataServiceApi_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API

#import "GTLDataServiceApiConstants.m"

#import "GTLDataServiceApiVoca.m"
#import "GTLDataServiceApiVocaCollection.m"

#import "GTLQueryDataServiceApi.m"
#import "GTLServiceDataServiceApi.m"
